### ISSUE TITLE
Anisette_server crashes on Apple Silicon Linux - loading openssl: unknown version for init

### ISSUE THREAD

**Issue by dylanchapell** [Dadoum/Provision#103]
I am running anisette_server on Asahi Linux (aarch64 fedora running on a M1 Macbook Air). I am attempting to run SideServer for linux and as a first step I am trying to get anisette_server to run. I extracted the apple music apk file to get the armv8 library, and downloaded the aarch64 version of anisette_server. When I run the binary it crashed with the following output:
`object.Exception@/github/home/.dub/packages/requests-2.0.9/requests/source/requests/ssl_adapter.d(197): loading openssl: unknown version for init`
This seems to be an error in requests-dlang, so let me know if I should report the issue there instead. 
The openssl and openssl-devel Fedora 39 packages are installed.

**Comment by dylanchapell** [comment]
Confirmed fixed. Compiled from source and now anisette_server runs. Thank you.

**Comment by Dadoum** [comment]
I recommend the use of Sideloader (check my GitHub) and SideStore anyway, as AltLinux is unmaintained currently.

**Comment by dylanchapell** [comment]
Oh yes, [SideServer-for-Linux](https://github.com/SideStore/SideServer-for-Linux) is what I am using

**Comment by Dadoum** [comment]
https://github.com/Dadoum/Sideloader ← this one is the only one really maintained
