### ISSUE TITLE
loading openssl: unknown version for init

### ISSUE THREAD

**Issue by babaruh** [Dadoum/Provision#104]
OS: Archlinux 6.7.4-arch1-1

I want to use this anisette server cause NyaMisty server seems like not up to date(so not working). I got `Incorrect Content-Type: must be textual to extract_string, JSON to extract_json.`
I tried version 2.1.0 and it runs but I got same error as with NyaMisky anisette server in AltStore

# Steps to reproduce
1. change permissions in order to run it from terminal
```
$ chmod +111 anisette-server
```
2. run it on port 6969
```
$ ./anisette-server -n 127.0.0.1 -p 6969
```
3. get error
`object.Exception@../../../.dub/packages/requests-2.0.9/requests/source/requests/ssl_adapter.d(197): loading openssl: unknown version for init`

**Comment by Dadoum** [comment]
Don't use an old version (it won't be able to use the newer libraries installed on your system), instead use the  latest GitHub actions build

**Comment by hmlendea** [comment]
The artifacts have expired though. Any idea why they aren't uploaded as a new release instead?
