### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by xliee** [Dadoum/Provision#12]
```
Loading ADI... done !
Loading Routing info... done !
Starting server... 
        # Archttp service has been started!
        - IO threads: 12
        - Listening: 0.0.0.0:6969

[127.0.0.1 >>] GET /
Segmentation fault
```

Get segmentation fault on / and /reprovision

added some prints to debug it:
```
    stderr.write("Loading ADI... ");
    auto app = new Archttp;
    ADI* adi = new ADI(expandTilde("~/.adi"));
    stderr.writeln("done !");

    ulong rinfo;
    if (!adi.isMachineProvisioned()) {
        stderr.write("Machine requires provisioning... ");
        adi.provisionDevice(rinfo);
        stderr.writeln("done !");
    } else {
        stderr.write("Loading Routing info... ");
        adi.getRoutingInformation(rinfo);
        stderr.writeln("done !");
    }
```
It raises Segmentation Fault at some point in the lib/provision/adi.d file.

uname .a:
`Linux Ninehy 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

Tried with libs from apk 3.10.1 and 3.10
Tried the precompiled version and the one i compiled and i get segmentation fault on both.

**Comment by Dadoum** [comment]
Can you share the core dump with me ?

**Comment by lilili87222** [comment]
It seems read ~/adi/adi.pb fail  .  delete adi.pb ,it works again but fail if adi.pb exist.

**Comment by Dadoum** [comment]
Can you clean and rebuild ? It should work now.

**Comment by Dadoum** [comment]
(or wait for the latest action to end to download it)

**Comment by Dadoum** [comment]
Should be fix, re-open an issue if it still happens
