### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JJTech0130** [Dadoum/Provision#13]
Sorry if I just missed something, but it’s not entirely clear what license this is under. I see it has a Boost dependency, but not what this whole repo is under.
Would be great if you could clarify.

**Comment by Dadoum** [comment]
Everything is LGPLv2 except Sideload IPA which is GPLv2. I should clarify that by adding headers.
However, if someone do need another license for the library, I can probably relicense it as long it is a libre license (feel free to open a discussion).
