### ISSUE TITLE
FAILED: retrieve_headers 

### ISSUE THREAD

**Issue by AlyafeiAli** [Dadoum/Provision#15]
Hi, I'm using Raspbian Buster 64 bit on a Raspberry Pi 4.
I am getting this error when I run the last step `ninja`  :

[3/1328] Linking D executable retrieve_headers
FAILED: retrieve_headers 
: && /home/pi/dlang/ldc-1.30.0/bin/ldc2 -O -release  CMakeFiles/retrieve_headers.dir/retrieve_headers/app.o -ofretrieve_headers  libprovision.a  /usr/local/lib/libplist-2.0.so  _deps/libhybris-build/libhybris.a  -L-lstdc++  -L-lpthread  -L-lrt  && :
/usr/bin/ld: libprovision.a(package.o): in function `_D9provision5plist5Plist5toXmlMFZAya':
package.d:(.text._D9provision5plist5Plist5toXmlMFZAya+0x58): undefined reference to `plist_to_xml_free'
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
[8/1328] Building D object _deps/gtk-d...ated/sourceview/gsv/SourceFileLoader.o
ninja: build stopped: subcommand failed.

Could you please tell me how I can fix this issue?
Thank you in advance!

**Comment by Dadoum** [comment]
Install the latest version of libplist from [here](https://github.com/libimobiledevice/libplist/releases) (2.2.0).

**Comment by AlyafeiAli** [comment]
> Install the latest version of libplist from [here](https://github.com/libimobiledevice/libplist/releases) (2.2.0).

Thanks for the quick reply.
I actually have built the latest version from that repo myself:
![image](https://user-images.githubusercontent.com/52626961/181908833-4cc36a5e-aaa9-43e7-a7b8-0d323b5dfab5.png)

**Comment by AlyafeiAli** [comment]
Update: I've reinstalled libplist and it looks like it's working! (Reached 455/1391)

I'll keep you posted

**Comment by AlyafeiAli** [comment]
Sadly, it failed at 1262/1391 with these errors among others:

full log: https://pastebin.com/h4zrXdwg

/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Error: /usr/bin/cc failed with status: 1
[1258/1391] Building D object _deps/ge.../geario/codec/textline/TextLineCodec.o
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74): Deprecation: `catch` statement without an exception specification is deprecated
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74):        use `catch(Throwable)` for old behavior
[1259/1391] Building D object _deps/ge...eario/codec/textline/TextLineDecoder.o
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74): Deprecation: `catch` statement without an exception specification is deprecated
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74):        use `catch(Throwable)` for old behavior
[1260/1391] Building D object _deps/ge...r/source/geario/event/selector/Epoll.o
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74): Deprecation: `catch` statement without an exception specification is deprecated
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74):        use `catch(Throwable)` for old behavior
[1261/1391] Building D object _deps/ge...ource/geario/event/selector/Selector.o
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74): Deprecation: `catch` statement without an exception specification is deprecated
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74):        use `catch(Throwable)` for old behavior
[1262/1391] Building D object _deps/ar...s/archttp.dir/source/archttp/Archttp.o
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74): Deprecation: `catch` statement without an exception specification is deprecated
/home/pi/Provision/build/_deps/nbuff_proj-src/source/nbuff/buffer.d(74):        use `catch(Throwable)` for old behavior
'-sse4.2' is not a recognized feature for this target (ignoring feature)
SSE: false
ninja: build stopped: subcommand failed.

**Comment by Dadoum** [comment]
You should install `libgmp-dev` on your raspberry pi

**Comment by Dadoum** [comment]
But you don't actually need it. Just write `ninja anisette_server` and it will just compile the anisette server. (Since GMP is needed for Sideload IPA, which is GUI app that you surely do not need).

**Comment by AlyafeiAli** [comment]
Thanks for the tip.
It did build anisette_server successfuly, but when I execute I get this error:

WARN: Generation of unique identifier failed, using a generic one instead. 
Segmentation fault

This is the output of when I was building it: https://pastebin.com/aeY9Lvse

![image](https://user-images.githubusercontent.com/52626961/181916549-ab4517df-abd0-45ab-8a95-36530fc4e3ff.png)

**Comment by Dadoum** [comment]
Build it in debug mode  (like this:
```
cmake -G Ninja ..
ninja
```
)
And then post the output here.

**Comment by AlyafeiAli** [comment]
The output of `cmake -G Ninja ..` : https://pastebin.com/WLMuuQrZ
The output of `ninja` : https://pastebin.com/3zwbD7R9
For some reason, it failed to build anisette_server this time

**Comment by Dadoum** [comment]
Okay, fixed the issue. do `rm -rf ./_deps/libhybris*` and re-run ninja.

**Comment by AlyafeiAli** [comment]
This is the output of running `ninja` again after running `rm -rf ./_deps/libhybris*` : https://pastebin.com/SNW0vcfL
The output of running ./anisette_server:

`(ldc-1.30.0)pi@raspberrypi:~/Provision/build2 $ ./anisette_server
WARN: Generation of unique identifier failed, using a generic one instead. 
Segmentation fault`

It gives the same error without any extra info

**Comment by Dadoum** [comment]
can you give me thr output of `file anisete_server` ?

**Comment by AlyafeiAli** [comment]
It says:

anisette_server: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=08cf50fbba8cb53d66798b4e4cccfbc93abc160b, for GNU/Linux 3.7.0, not stripped

**Comment by Dadoum** [comment]
It's weird, it stills not include debug_info. 

Anyway, I noticed that someone built everything in debug mode [here](https://github.com/Zoltan-Balazs/Provision), so can you provide me the output of this anisette_server ?

**Comment by AlyafeiAli** [comment]
> It's weird, it stills not include debug_info.
> 
> Anyway, I noticed that someone built everything in debug mode [here](https://github.com/Zoltan-Balazs/Provision), so can you provide me the output of this anisette_server ?

It gives this error:

./anisette_server2: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette_server2)
./anisette_server2: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette_server2)
./anisette_server2: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./anisette_server2)

**Comment by Dadoum** [comment]
attempted a fix, please retry building (in debug mode) with latest source

**Comment by AlyafeiAli** [comment]
> attempted a fix, please retry building (in debug mode) with latest source

I really appreciate your help, thank you again
Just to be clear, it'll be in debug mode if I don't type `-DCMAKE_BUILD_TYPE=Release` , right?
I only have to `cmake -G Ninja ..` and then `ninja`

**Comment by Dadoum** [comment]
Yes, but if you want to be sure you can also write -DCMAKE_BUILD_TYPE=Debug (it should also build faster)

**Comment by AlyafeiAli** [comment]
I'm getting this now:

Cannot load fstat from libc ! 
Cannot load lstat from libc ! 
Loading Android-specific symbols...
Loading ADI symbols...
Generating an identifier...
WARN: Generation of unique identifier failed, using a generic one instead. 
First calls...
Setting fields...
Ctor done !
isMachineProvisioned called !
Segmentation fault

**Comment by Dadoum** [comment]
Okay, that's the same issue as #9, I commited another attempt to fix it.

**Comment by Dadoum** [comment]
I am not happy with the fix I made anyway, so if it works I will still try something else.

**Comment by AlyafeiAli** [comment]
I deleted the whole directory and cloned it again for the last commit, but it's still showing the same exact error message unfortunately

**Comment by Dadoum** [comment]
You can just write `git pull` to update code. I pushed another commit, hopefully working this time. (or at least making lstat and fstat errors disappear)

**Comment by AlyafeiAli** [comment]
Good to know, thanks!
I'll try it and get back to you 👍🏻

**Comment by AlyafeiAli** [comment]
You're a genius!
It finally worked, thank you so much I really do appreciate it ♥️

![Screenshot_20220731-011942_VNC Viewer](https://user-images.githubusercontent.com/52626961/181996547-5523dca8-0c31-44f0-b18e-f86640b74ca5.jpg)

**Comment by Dadoum** [comment]
Thanks a lot ! <3 It was a persisting issue in Provision, and without your help it would have taken much longer to fix it (I think it's the same problem as the #9, but since it seems we were in totally opposed timezone it was harder to fix).

**Comment by AlyafeiAli** [comment]
Glad I was of help!
I can finally sleep lol
Good night :)
