### ISSUE TITLE
@onServerInit vs @onWorkerStart

### ISSUE THREAD

**Issue by trikko** [Dadoum/Provision#17]
I think you want to run this initialization inside a function marked with UDA @onWorkerStart .

https://github.com/Dadoum/Provision/blob/57e9feed81e97b2f422a0528bc62c25f26cd1d47/anisette_server/app.d#L15

Functions marked with @onServerInit are executed just one time by the daemon not by the process that reply to your http request.

```d
// This function will be called for each worker
@onWorkerStart void yourInitFunction()
{
    adi = new ADI(expandTilde("~/.adi"));

    if (!adi.isMachineProvisioned()) {
        stderr.write("Machine requires provisioning... ");
        adi.provisionDevice(rinfo);
        stderr.writeln("done !");
    } else {
        // adi.getRoutingInformation(rinfo);
        rinfo = 0;
    }
}
```

**Comment by Dadoum** [comment]
Yes but it only needs to be run one time at the beginning. Except if I did not understand how works workers

**Comment by trikko** [comment]
Workers are separated processes, started by the daemon.

When a worker start @onWorkerStart is called. Just one time for each worker.

**Comment by Dadoum** [comment]
That's problematic since it seems that I can only use one ADI handle at a time, or it will break. How can I do. 

When I compare my old archttp implementation with the new experimental serverino one, I can see that the older one always respond with the needed data while the serverino will fail and break after few requests.

Tested by running this command to stress test the server:
```
curl 127.0.0.1:6969 & curl 127.0.0.1:6969 &curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 & curl 127.0.0.1:6969 &
```

**Comment by trikko** [comment]
```That's problematic since it seems that I can only use one ADI handle at a time, or it will break. How can I do.```

But they live in different processes. They is no data shared between responders. Each responder is completly isolated. If you run 4 responder, you're running 4 different instances each one with a single ADI handle. Is this a problem?

**Comment by Dadoum** [comment]
I don't really know how ADI exactly works. What I described is not related to the location of the ADI instructions (if they are in onServerInit or in onWorkerStart), it happens with both locations. The only thing I really know is that ADI functions break with the serverino version, and that ADI interracts with a file on the filesystem located at `~/.adi/adi.pb`.

**Comment by Dadoum** [comment]
Switching back to archttp for now.
