### ISSUE TITLE
Loaded function names

### ISSUE THREAD

**Issue by JJTech0130** [Dadoum/Provision#18]
I've been looking into this, and I'm a tad confused.
When you're loading functions, you have lines like this:
```D
this.pADIProvisioningErase = cast(ADIProvisioningErase_t) libstoreservicescore.load("p435tmhbla");
```
Is `p435tmhbla` the function name, just obfuscated? Or is it some other kind of identifier for loading the function? When not using libhybris (like say you wanted to use it in C++ on android), would you literally just call `p435tmhbla()`?

Additionally, how does the loading of `libCoreADI.so` work? I see that you store it in a variable, but I can't find how it gets used? Does loading it just magically make it available to `libstoreservicescore` as a dep.?

**Comment by Dadoum** [comment]
Yes, Apple obfuscate names of the ADI functions. These functions are 1:1 equivalent to AKADIProxy functions on iOS, and they are quite consistent on the naming, since these function names does not change neither across versions nor across different Apple apps. On Android, you can call with their obfuscate name even if an alias would be preferable for readability. 

libstoreservicescore automatically tries to load libCoreADI from the standard paths when you initialize it. You can specify a custom path if you want libCoreADI to be stored somewhere else. If it's already loaded in the memory it will be able to use it without complaining, so I load it to be sure before loading libstoreservicescore.

On Android and arm devices you can use the Apple TV app's libCoreADI. It directly exports the functions with the same mangled names, reducing even further the size required on the disk.

**Comment by JJTech0130** [comment]
This would work as a header, right?:
```c++
// libstoreservicescore.h

// Obfuscated symbols
#define LoadLibraryWithPath kq56gsgHG6
#define SetAndroidID Sph98paBcz
#define SetProvisioningPath nf92ngaK92

#define ProvisioningErase p435tmhbla
#define Synchronize tn46gtiuhw
#define ProvisioningDestroy fy34trz2st
#define ProvisioningEnd uv5t6nhkui
#define ProvisioningStart rsegvyrt87
#define GetLoginCode aslgmuibau
#define Dispose jk24uiwqrg
#define OTPRequest qi864985u0
#define SetIDMSRouting ksbafgljkb
#define GetIDMSRouting madsvsfvjk

// Android-specific symbols
int LoadLibraryWithPath(const char*);
int SetAndroidID(const char*, uint);
int SetProvisioningPath(const char*);

// ADI symbols
int ProvisioningErase(ulong);
int Synchronize(uint, ubyte*, uint, ubyte**, uint*, ubyte**, uint*);
int ProvisioningDestroy(uint);
int ProvisioningEnd(uint, ubyte*, uint, ubyte*, uint);
int ProvisioningStart(ulong, ubyte*, uint, ubyte**, uint*, uint*);
int GetLoginCode(ulong);
int Dispose(void*);
int OTPRequest(ulong, ubyte**, uint*, ubyte**, uint*);
int SetIDMSRouting(ulong, ulong);
int GetIDMSRouting(ulong*, ulong);
```

**Comment by Dadoum** [comment]
Yes, here is one with params names and types corrected:
```c
// libstoreservicescore.h

// Obfuscated symbols
#define LoadLibraryWithPath kq56gsgHG6
#define SetAndroidID Sph98paBcz
#define SetProvisioningPath nf92ngaK92

#define ProvisioningErase p435tmhbla
#define Synchronize tn46gtiuhw
#define ProvisioningDestroy fy34trz2st
#define ProvisioningEnd uv5t6nhkui
#define ProvisioningStart rsegvyrt87
#define GetLoginCode aslgmuibau
#define Dispose jk24uiwqrg
#define OTPRequest qi864985u0
#define SetIDMSRouting ksbafgljkb
#define GetIDMSRouting madsvsfvjk

// Android-specific symbols
int LoadLibraryWithPath(const char *libraryPath);
int SetAndroidID(const char *identifier, unsigned int length);
int SetProvisioningPath(const char *provisioningPath);

// ADI symbols
int ProvisioningErase(unsigned long long);
int Synchronize(unsigned long long, const char *SIM, unsigned int SIMLength, char **outMID, unsigned int *outMIDLength, char **outSRM, unsigned int *outSRMLength);
int ProvisioningDestroy(unsigned int session);
int ProvisioningEnd(unsigned int session, const char *PTM, unsigned int PTMLength, const char *TK, unsigned int TKLength);
int ProvisioningStart(unsigned long long dsId, const char *SPIM, unsigned int SPIMLength, char **CPIM, unsigned int *CPIMLength, unsigned int *session);
int GetLoginCode(unsigned long long dsId);
int Dispose(void *data);
int OTPRequest(unsigned long long dsId, char **outMID, unsigned int *outMIDSize, char **outOTP, unsigned int *outOTPSize);
int SetIDMSRouting(unsigned long long routingInfo, unsigned long long dsId);
int GetIDMSRouting(unsigned long long *routingInfo, unsigned long long dsId);
```

**Comment by JJTech0130** [comment]
Thanks! I totally forgot about adding names lol, I just put your code in a comment and had Copilot fill it in.

**Comment by JJTech0130** [comment]
One thing I'm noticing, is that you have a function called `int GetLoginCode(unsigned long long dsId);`, wheras the original has `+ (int)isMachineProvisioned:(unsigned long long)arg1;`. I'm assuming they're different? or are they the same thing

**Comment by Dadoum** [comment]
They are the same function, but ADIGetLoginCode is its internal name in the C API while isMachineProvisioned is its name in Objective-C.

**Comment by Dadoum** [comment]
If you need more assistance you can contact me on Discord Dadoum#9690
