### ISSUE TITLE
Automatically download and extract APK

### ISSUE THREAD

**Issue by JJTech0130** [Dadoum/Provision#19]
Would it be possible to automatically download and extract the APK? Apple provides an official download now: https://apps.mzstatic.com/content/android-apple-music-apk/applemusic.apk it includes the .so files for every architecture

**Comment by Dadoum** [comment]
Yes it is. I am currently trying to download only part of the APK, because I think it should not download 127 MB while we only need few files.

**Comment by JJTech0130** [comment]
Yeah. If Apple's server supports content-range, that should be possible, right?

**Comment by Dadoum** [comment]
It seems that Apple supports Content-Range only with gzipped requests, but we can't unzip a part of gzip file, so it seems impossible…

**Comment by Macleykun** [comment]
Perhaps using a docker image to make the download as small as possible is an idea :)
i'm working on it, it does work but have to write it up nicely.

I do have one question, you have any clue why this happens in alpine but not ubuntu?
```
/test # ./anisette_server-aarch64
/bin/sh: ./anisette_server-aarch64: not found
/test # sh anisette_server-aarch64
anisette_server-aarch64: line 1:ELF▒▒▒@▒L▒@8: not found
anisette_server-aarch64: line 2: syntax error: unexpected ")"
```
it's not a big issue, but i like to use alpine for docker images :)

**Comment by JJTech0130** [comment]
> It seems that Apple supports Content-Range only with gzipped requests, but we can't unzip a part of gzip file, so it seems impossible…
Wait, so I don't actually get why this is a problem. The GZIP compression is applied on the HTTP level, on top of the ZIP compression of the APK. Thus, simply wrap the partial ZIP requests in a GZIP decompression.

**Comment by Dadoum** [comment]
> Perhaps using a docker image to make the download as small as possible is an idea :) i'm working on it, it does work but have to write it up nicely.
> 
> I do have one question, you have any clue why this happens in alpine but not ubuntu?
> 
> ```
> /test # ./anisette_server-aarch64
> /bin/sh: ./anisette_server-aarch64: not found
> /test # sh anisette_server-aarch64
> anisette_server-aarch64: line 1:ELF▒▒▒@▒L▒@8: not found
> anisette_server-aarch64: line 2: syntax error: unexpected ")"
> ```
> 
> it's not a big issue, but i like to use alpine for docker images :)

I guess it's related to interpreter? Is the file `/lib/ld-linux-aarch64.so.1` on your system? if not, type `file /bin/sh` and see the interpreter name, and then use `patchelf --set-interpreter <interpreter name> ./anisette-server`  to change the one specified in the original file.

**Comment by Dadoum** [comment]
> > It seems that Apple supports Content-Range only with gzipped requests, but we can't unzip a part of gzip file, so it seems impossible…
> 
> Wait, so I don't actually get why this is a problem. The GZIP compression is applied on the HTTP level, on top of the ZIP compression of the APK. Thus, simply wrap the partial ZIP requests in a GZIP decompression.
> 
> That's why `curl`'s `--compressed` flag works: it can transparently decrypt the entire GZIP compression, even when the request is only partial.

I should take a look, especially since I am working on a full AltServer reimplementation.

**Comment by JJTech0130** [comment]
> > > It seems that Apple supports Content-Range only with gzipped requests, but we can't unzip a part of gzip file, so it seems impossible…
> > 
> > 
> > Wait, so I don't actually get why this is a problem. The GZIP compression is applied on the HTTP level, on top of the ZIP compression of the APK. Thus, simply wrap the partial ZIP requests in a GZIP decompression.
> > That's why `curl`'s `--compressed` flag works: it can transparently decrypt the entire GZIP compression, even when the request is only partial.
> 
> I should take a look, especially since I am working on a full AltServer reimplementation.

Now I'm confused: I was trying this, and I can't get it to work. Now that I'm looking at it, maybe it *does* do gzip on the whole thing, and I was just mixing up it and Transfer-Encoding (which doens't affect Apple's server)

**Comment by JJTech0130** [comment]
So... I have an idea.
It looks like you can generate an *index* for a GZIP file, which lets you seek through it like a ZIP.
So, we could host that index, and it wouldn't actually contain the file, just the index to let it unzip parts of the gzip.
Then, you could use a partial zip algorithm on those.

It would be kinda complex tho, might just be easier to bite the bullet and download all 100 some MB

**Comment by Macleykun** [comment]
> So... I have an idea. It looks like you can generate an _index_ for a GZIP file, which lets you seek through it like a ZIP. So, we could host that index, and it wouldn't actually contain the file, just the index to let it unzip parts of the gzip. Then, you could use a partial zip algorithm on those.
> 
> It would be kinda complex tho, might just be easier to bite the bullet and download all 100 some MB

i think it might be better to just download it all. They only have to download it once anyways :)

**Comment by JJTech0130** [comment]
This is done in the Docker image, so I'm going to close this issue.
