### ISSUE TITLE
anisette_server does not work on Raspberry Pi 4

### ISSUE THREAD

**Issue by lonsdaleite** [Dadoum/Provision#20]
When I'm trying to run anisette server on my RPI 4, it won't start:
```
pi@raspberrypi:~/altserver $ ./anisette_server-aarch64 
./anisette_server-aarch64: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./anisette_server-aarch64)
./anisette_server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette_server-aarch64)
./anisette_server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette_server-aarch64)
./anisette_server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette_server-aarch64)
```

I've upgraded all packages using sudo apt upgrade. I can't find newer libstdc++.so.6 and libc.so.6 libs for RPI 4.
I've also tried to compile the anisette server using cmake, but there is some problem with D compiler, I couldn't find any which would work with the project.

Any ideas?

**Comment by Dadoum** [comment]
Yes the required Glibc required for the built executable are very recent (requires Ubuntu 22.04). 
If you want to build it, try to install ldc2. 
```
sudo apt install ldc2
```
then add `-DCMAKE_D_COMPILER=ldc2` to the cmake command. (and ensure you cloned the repository with the `--recursive` flag, if not, type `git submodule update --init` in your terminal before running CMake command).

If it still fails, copy the terminal output here and I will help you.

**Comment by lonsdaleite** [comment]
ldc2 already installed

`pi@raspberrypi:~/altserver/Provision/build $ cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_D_COMPILER=ldc2
-- The D compiler identification is LDC
-- Check for working D compiler: /usr/bin/ldc2
-- Check for working D compiler: /usr/bin/ldc2 -- broken
-- To force a specific D compiler set the DC environment variable
--     ie - export DC="/usr/bin/dmd"
CMake Error at cmake/cmake-d/cmake-d/CMakeTestDCompiler.cmake:49 (message):
  The D compiler "/usr/bin/ldc2" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /home/pi/altserver/Provision/build/CMakeFiles/CMakeTmp

  

  Run Build Command(s):/usr/bin/ninja cmTC_8055b && [1/2] Building D object
  CMakeFiles/cmTC_8055b.dir/testDCompiler.o

  FAILED: CMakeFiles/cmTC_8055b.dir/testDCompiler.o

  /usr/bin/ldc2 -makedeps=CMakeFiles/cmTC_8055b.dir/testDCompiler.o.d
  -ofCMakeFiles/cmTC_8055b.dir/testDCompiler.o -c
  /home/pi/altserver/Provision/build/CMakeFiles/3.24.0/CMakeTmp/testDCompiler.d


  ldc2: Unknown command line argument
  '-makedeps=CMakeFiles/cmTC_8055b.dir/testDCompiler.o.d'.  Try:
  '/usr/bin/ldc2 --help'

  ldc2: Did you mean '--deps=CMakeFiles/cmTC_8055b.dir/testDCompiler.o.d'?

  ninja: build stopped: subcommand failed.

  

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)


-- Configuring incomplete, errors occurred!
See also "/home/pi/altserver/Provision/build/CMakeFiles/CMakeOutput.log".
`

`pi@raspberrypi:~/altserver/Provision/build $ cat /home/pi/altserver/Provision/build/CMakeFiles/CMakeOutput.log
The system is: Linux - 5.15.32-v8+ - aarch64
Compiling the D compiler identification source file "CMakeDCompilerId.d" succeeded.
Compiler: /usr/bin/ldc2 
Build flags: 
Id flags:  

The output was:
0


Compilation of the D compiler identification source "CMakeDCompilerId.d" produced "CMakeDCompilerId"

Compilation of the D compiler identification source "CMakeDCompilerId.d" produced "CMakeDCompilerId.o"

The D compiler identification is LDC, found in "/home/pi/altserver/Provision/build/CMakeFiles/3.24.0/CompilerIdD/CMakeDCompilerId"

Compiling the D compiler identification source file "CMakeDCompilerId.d" succeeded.
Compiler: /usr/bin/ldc2 
Build flags: 
Id flags:  

The output was:
0


Compilation of the D compiler identification source "CMakeDCompilerId.d" produced "CMakeDCompilerId"

Compilation of the D compiler identification source "CMakeDCompilerId.d" produced "CMakeDCompilerId.o"

The D compiler identification is LDC, found in "/home/pi/altserver/Provision/build/CMakeFiles/3.24.0/CompilerIdD/CMakeDCompilerId"
`

**Comment by Dadoum** [comment]
Yes, your compiler is too old too. You must install a more recent compiler on your device.

Use `curl -fsS https://dlang.org/install.sh | bash -s ldc` to install a more recent compiler.

**Comment by lonsdaleite** [comment]
@Dadoum, thanks, I've compiled it successfully.
Now I have the same issue as in #21

**Comment by Dadoum** [comment]
I replied in the issue to diagnose the issue (I will close this one to avoid duplicated discussions)
