### ISSUE TITLE
Segmentation Fault Issue

### ISSUE THREAD

**Issue by Nythepegasus** [Dadoum/Provision#21]
Hello! I am building the x86_64 version on Void Linux, and every time I try to run any of the executables I get segmentation faults. Below are both outputs from `anisette_server`.

Building for release gives me:
```
"/home/ny/workspace/altstuff/Provision/build/lib/x86_64/libCoreADI.so" phdr mmap failed: Invalid argument
Segmentation fault
```

Then a debug release gives me:
```
"/home/ny/workspace/altstuff/Provision/build2/lib/x86_64/libCoreADI.so" phdr mmap failed: Cannot allocate memory
Segmentation fault
```

Am I getting the APK from the wrong location, or am I doing something else wrong?

**Comment by Dadoum** [comment]
What happens when you remove `return false;` at line 340 in `/home/ny/workspace/altstuff/Provision/build/_deps/libhybris-src/linker/linker_phdr.cpp` ? Does it fix the issue ?

**Comment by lonsdaleite** [comment]
Now I've got this:
```
pi@raspberrypi:~/altserver/anisette $ ./anisette_server
"/home/pi/altserver/anisette/lib/arm64-v8a/libCoreADI.so" phdr mmap failed: Invalid argument
"/home/pi/altserver/anisette/lib/arm64-v8a/libCoreADI.so" shdr mmap failed: Invalid argument
Segmentation fault
```
I've tried to remove `return false;` at 366 line too, but nothing changed.

**Comment by Dadoum** [comment]
Is this happening with the 1.0.0 version (clone the 1.0.0 tag) ?

**Comment by lonsdaleite** [comment]
Yes, the same behaviour with 1.0.0

**Comment by Nythepegasus** [comment]
> What happens when you remove `return false;` at line 340 in `/home/ny/workspace/altstuff/Provision/build/_deps/libhybris-src/linker/linker_phdr.cpp` ? Does it fix the issue ?

I commented the line, and I get the behavior @lonsdaleite is getting:
```
"/home/ny/workspace/altstuff/Provision/build/lib/x86_64/libCoreADI.so" phdr mmap failed: Invalid argument
"/home/ny/workspace/altstuff/Provision/build/lib/x86_64/libCoreADI.so" shdr mmap failed: Invalid argument
Segmentation fault
```
and debug build returns:
```
"/home/ny/workspace/altstuff/Provision/build2/lib/x86_64/libCoreADI.so" phdr mmap failed: Cannot allocate memory
"/home/ny/workspace/altstuff/Provision/build2/lib/x86_64/libCoreADI.so" shdr mmap failed: Cannot allocate memory
Segmentation fault
```
I have not tried 1.0.0, i'll try that next and report back.

**Comment by Dadoum** [comment]
Managed to reproduce the issue, I will investigate

**Comment by Dadoum** [comment]
Fixed !
