### ISSUE TITLE
AltStore "not an object" error on refresh

### ISSUE THREAD

**Issue by andre1808** [Dadoum/Provision#26]
Hey.

I've managed to get provision working on my RPI4 running ubuntu 22.04.1.
I've downloaded the arch64 version from [here](https://github.com/Dadoum/Provision/actions/runs/3435864794)

But unfortunately, when I try to refresh on my iPhone, I receive an "not an object" error.
The request seems to be received by provision.
Not sure how senstive this data is, so I'll remove the cryptic part from the output in my terminal session:
`[<<] GET /
[>>] 200 OK {"X-Apple-I-Client-Time":"2022-11-20T14:55:07Z","X-Apple-I-MD":"****","X-Apple-I-MD-LU":"****","X-Apple-I-MD-M":"****","X-Apple-I-MD-RINFO":"****","X-Apple-I-SRL-NO":"0","X-Apple-I-TimeZone":"CEST","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<iMac11,3> <Mac OS X;10.15.6;19G2021> <com.apple.AuthKit\/1 (com.apple.dt.Xcode\/3594.4.19)>","X-Mme-Device-Id":"****"}
`

I've an anisette server on my QNAP NAS (Container Station) and when I use this anisette server it's working. The output looks very similar:
`{"X-Apple-I-Client-Time":"2022-11-20T13:44:57Z","X-Apple-I-MD":"****","X-Apple-I-MD-LU":"","X-Apple-I-MD-M":"****","X-Apple-I-MD-RINFO":"****","X-Apple-I-SRL-NO":"****","X-Apple-I-TimeZone":"PST","X-Apple-Locale":"en_US","X-MMe-Client-Info":"<MacBookPro15,1> <Mac OS X;10.15.2;19C57> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>","X-Mme-Device-Id":"****"}`

Do you have any idea how to overcome this error?

Thank you already!

BR
André

**Comment by Dadoum** [comment]
Provision works correctly here, it's probably an error in AltServer-Linux, do you have its output?

**Comment by andre1808** [comment]
Sure. That's the output:
Other Socket:7. Port: 54559. Error: 0
Receiving request size...
Checking socket: 7
Received bytes: 4(of 4)
Receiving 48 bytes...
Checking socket: 7
Received bytes: 48(of 48)
Received response status code: 200
parse anisette data ret
Got anisetteData json: null
Represented Value: 183
Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
FaiSent Bytes Count: 183 (183)
Sent Data: 183le Bytes
d to handle request:not an object

**Comment by andre1808** [comment]
Found the "problem".
The file [I've downloaded from Actions ](https://github.com/Dadoum/Provision/actions/runs/3435864794) for some reason doesn't work for me.
However the one from the [releases section](https://github.com/Dadoum/Provision/releases/tag/1.0.0) does!
Finally got the entire AltStore stuff running on one raspbery pi!

Thank you so much for your work!

**Comment by Dadoum** [comment]
Okay, I will leave this issue open, since this seems to be a real issue requiring investigation. Will take a look when I will have time.

<3 thank you for using my project

**Comment by Dadoum** [comment]
Can you retry with latest binary?

**Comment by andre1808** [comment]
Tried the arch64 version from here[Here](https://github.com/Dadoum/Provision/actions/runs/3587292029) and it seems to be working. 

I’ve changed to SideStore though and gave it a try using this app. And it did refresh just fine.

**Comment by Dadoum** [comment]
Okay perfect! (I will close the issue, feel free to open a new one if a new issue arise)
