### ISSUE TITLE
[anisette_server] not an object error on AltServer-Linux

### ISSUE THREAD

**Issue by maxduke** [Dadoum/Provision#33]
I'm using the latest docker image. Altstore issue the error "not a object".
I compared that to a worked anisette_server and found the difference, but I'm not sure if that is the root cause.

Resutls from curl:
Worked one:
![image](https://user-images.githubusercontent.com/440836/205201141-557bcf1f-7b0f-418a-833b-f90fa952104c.png)
dadoum/anisette-server:
![image](https://user-images.githubusercontent.com/440836/205201192-4057ab6e-dfa8-47c3-ad0d-fd0a9fc5fc7c.png)

**Comment by JJTech0130** [comment]
If you’re pointing out the Client Info, it’s basically a User Agent, and shouldn’t affect anything unless your AltStore is doing something extremely weird. It’s probably the HTTP issue again…

**Comment by the-eternel** [comment]
I have the same result with the last build and compare the the alt server-linux default anisette server (https://armconverter.com/anisette/irGb3Quww8zrhgqnzmrx) it seems that the "X-Mme-Device-Id" value has not the same format:
armconverter: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
last build:        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by Dadoum** [comment]
Now it's fixed !
