### ISSUE TITLE
Segmentation fault      (core dumped) /opt/anisette_server

### ISSUE THREAD

**Issue by Macleykun** [Dadoum/Provision#39]
Spidy informed me that anisette that i was hosting was down, looking into it i had logging still on but only got this:
```
[>>] 200 OK {"X-Apple-I-Client-Time":"2022-12-18T00:38:33Z","X-Apple-I-
(truncated as i'm not sure if this is personal info)
[<<] GET /
/opt/docker-entrypoint.sh: line 17:     9 Segmentation fault      (core dumped) /opt/anisette_server
[>>] 200 OK {"X-Apple-I-Client-Time":"2022-12-18T00:40:41Z","X-Apple-I-
(truncated as i'm not sure if this is personal info)
requir                         es provisioning... done !
```
This is sadly all the details i have, The container was created 6 days ago and was up for 10 hours (i had to restart both to get all the package up to date on the hosts, the other DE is still running fine weirdly enough.

Is there smth i can edit in the docker-entrypoint script to catch a more meaningful error next time i have this?

**Comment by Dadoum** [comment]
you can switch the build-type to Debug (`-DCMAKE_BUILD_TYPE=Debug`) to log more things. It also allows you to take the core dump and analysing it after the crash.

**Comment by Macleykun** [comment]
gotcha, need to rebuild the image then with that included :) thx!

**Comment by Macleykun** [comment]
If it segfaults, where can i find the dump in the container :) ?

**Comment by Dadoum** [comment]
I don't know, apparently this is setuped like this https://ddanilov.me/how-to-configure-core-dump-in-docker-container

**Comment by Macleykun** [comment]
Gotcha! Thanks for that link as i didn't configure the container to catch that dump.
Now running both with:

docker run -d --mount type=bind,source=/tmp/,target=/tmp/ -v lib_cache:/opt/lib/ --ulimit core=-1 --restart=always -p 6969:6969 --name anisette macley/anisette-server:latest

Hopefully we can catch this (final) bug :)

**Comment by Macleykun** [comment]
i checked today but i saw the containers were running but i couldn't get any output from the port 6969. Doing a restart of the containers did work, but sadly, still haven't gotten anything yet i'm afraid.

**Comment by Macleykun** [comment]
I'll just restart the container every night, i think that's the best
