### ISSUE TITLE
Weird Error with libCoreADI

### ISSUE THREAD

**Issue by Jark5455** [Dadoum/Provision#44]
Hello, whenever I build and run the anisette server from the code I get this error

```
std.file.FileException@/home/jark/Provision/lib/provision/adi.d(120): lib/x86_64/libCoreADI.so: Apple libraries are not installed correctly. Refer to README for instructions. 
----------------
??:? shared ref shared(provision.adi.ADI) provision.adi.ADI.__ctor(immutable(char)[], char[]) [0x55a03bb61157]
??:? _Dmain [0x55a03bb44769]
```

I am willing to provide any debug info needed to fix this

**Comment by Dadoum** [comment]
You need to setup the libraries. It's a pretty straightforward process. Download [here](https://apps.mzstatic.com/content/android-apple-music-apk/applemusic.apk) the Apple Music apk. Then extract the lib/ folder and put it in `/home/jark/Provision/build` (next to the executable you built). Then it should work
