### ISSUE TITLE
HTTP Error in Docker

### ISSUE THREAD

**Issue by Al4ise** [Dadoum/Provision#48]
Running the latest image in docker gives this error:

Machine requires provisioning... std.net.curl.HTTPStatusException@/usr/lib/ldc/x86_64-linux-gnu/include/d/std/net/curl.d(1097): HTTP request returned status code 401 ()

The container infinitely restarts

**Comment by Dadoum** [comment]
Are you sure that you are using the latest docker image? I fixed the same bug one week ago, and it seems to work fine now on my computer.

**Comment by Al4ise** [comment]
It is the latest image, yeah. I pulled it again a few times just to make sure. Do you need other logs?

**Comment by Dadoum** [comment]
I think I know where it is happening… in which timezone you are?

**Comment by Al4ise** [comment]
EET(UTC+2)

**Comment by Al4ise** [comment]
actually nevermind, my server is in gmt-0

**Comment by Dadoum** [comment]
Is your server a locally hosted one? I think that Apple could have blocked few IPs here and there.

**Comment by Al4ise** [comment]
No, it’s on oracle cloud. Should I try to make a completely new server?

**Comment by Dadoum** [comment]
Can you try on your local computer, then on another oracle machine (if you can, otherwise I will try to figure out)

**Comment by Al4ise** [comment]
It works on the other machine. Maybe I really got blacklisted
