### ISSUE TITLE
Advanced Data Protection not supported?

### ISSUE THREAD

**Issue by Smethan** [Dadoum/Provision#53]
I saw in the commit history there was PR #41 which supposedly added support for ADP, but it was seemingly reverted one commit later since it broke things. Is ADP supported and I'm just missing something, or is it still in the works? As it stands, when I try to sign in referencing this as the anisette server, it asks for a 2fa code that never comes

**Comment by Dadoum** [comment]
I had to remove it because it was not functioning on my computer so I was not able to test the software. But apparently the patch still works for most people, so if needed, you can put back the client info to "<iMac20,2> <macOS;13.1;22C65> <com.apple.AuthKit/1 (com.apple.dt.Xcode/3594.4.19)>" (the `macOS` bit is important here, in the original commit it was broken)

**Comment by Smethan** [comment]
I tried that and it caused the same 401 error people were getting. I'm trying to see if I can compile it in debug mode to see whats going wrong, but cmake doesn't seem all too keen on working today

**Comment by Smethan** [comment]
So I finally got it to build via docker. It's still giving me the 401 error, looks like its dying in downloadSPIM. I can guess that this is part of setting up the fake device we're going to use to send our signing requests, so what could be missing? Both the client and xml data seem pretty simple, the only thing that really looks like it could be wrong is whatever is in urlBag. I don't know much about this whole anisette thing, so I'm kinda just spitballing here

**Comment by Dadoum** [comment]
You're probably right, I just have no device to sniff requests and try to replicate those. I am guessing that something changed with ADP devices but I don't know what.

**Comment by Smethan** [comment]
would you want to sniff requests while setting the device up, or while logging in to an apple id or what? I can give packet sniffing a go if you have an idea of what point I would want to sniff at

**Comment by Smethan** [comment]
Ah, thats what I was worried about. I will hunt around to see if there's a way to work around SSL pinning

**Comment by Smethan** [comment]
So, I was able to intercept some machine provisioning requests that I am guessing are what we're looking for, and there's a good bit of different stuff.
[[109] Request - gsa.apple.com_grandslam_MidService_startMachineProvisioning.txt](https://github.com/Dadoum/Provision/files/11054908/109.Request.-.gsa.apple.com_grandslam_MidService_startMachineProvisioning.txt)
Here's the request file for the startMachineProvisioning request, I also have the request for finishMachineProvisioning, but they're pretty much the same. I have signed out and back in to my account so theoretically this should be safe to post. The biggest standouts that I don't see in the current request are all the headers with -S appended to them, and the X-Apple-Baa header, which I'm guessing might be our culprit

**Comment by Dadoum** [comment]
(note: I have no ADP account to try if ADP actually works, but it should, they said on Apple website that all macs on 13.1 supports ADP)

**Comment by Smethan** [comment]
That change made it work for me! The part about them using Secure Enclave data is a bit worrisome. But they theoretically will still support iCloud on windows, which doesn't have that, so surely there will be a way around that, right?

**Comment by Dadoum** [comment]
> But they theoretically will still support iCloud on windows, which doesn't have that, so surely there will be a way around that, right?

Yeah but it seems that they are using a new specific library for that (kccadp). Doesn't seem impossible to replicate but I think that waiting for Apple Music for Android to be updated can probably save us some work. 

Anyway, let's profit while it's working.

**Comment by Smethan** [comment]
True, true, gotta enjoy it while it lasts :D
Thanks for the help on getting it working! I'll close this up now
