### ISSUE TITLE
Cannot create libraries folder folder. Hopefully everything still works. (Docker?)

### ISSUE THREAD

**Issue by Practicalbutterfly5** [Dadoum/Provision#59]
Recently I have started getting this error when making new containers.

Also the container will keep restarting, and keep pulling libraries from apple server unless the container is stopped.

```

~# docker run -d -v lib_cache:/opt/lib/ --restart=always -p 6969:6969 --name anisette dadoum/anisette-server:latest
cb8b027af1531f5b0e5fa7ba395d732268f855d2da27fe670416af199e15150b


~# docker logs anisette
Downloading libraries fromstd.file.FileException@std/file.d(836): lib/x86_64/libCoreADI.so: No such file or directory
----------------
??:? [0x558fb4257f46]
??:? [0x558fb425a3d6]
??:? [0x558fb4239e0f]
??:? [0x558fb4200a2a]
??:? [0x558fb416c49d]
??:? [0x558fb4239afb]
??:? [0x558fb42399f5]
??:? [0x558fb423984d]
??:? [0x7febb3663189]
??:? __libc_start_main [0x7febb3663244]
??:? [0x558fb416baf0]
Downloading libraries from Apple servers... done!         
Cannot create libraries folder folder. Hopefully everything still works. (Docker?)


```

ubuntu 22.04 amd64
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2

**Comment by Dadoum** [comment]
I am aware of that issue, this is happening with official docker when you use `-v lib_cache:/opt/lib/`. 

I will fix this soon (probably at the end of the week) but in the meantime here are two workarounds:
 - Don't cache library (so remove the `-v lib_cache:/opt/lib/ ` bit of the command)
 - Use podman which doesn't have this issue (I don't know why but it works fine on my computers with podman)
