### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by cccRaim** [Dadoum/Provision#71]
```
??:? [0x55716d7d3e56]
??:? [0x55716d7d62e6]
??:? [0x55716d7b5d1f]
??:? [0x55716d7425f3]
??:? [0x55716d74254d]
??:? [0x55716d795416]
??:? [0x55716d795238]
??:? [0x55716d6fd3ad]
??:? [0x55716d6e75e3]
??:? [0x55716d7b5a0b]
??:? [0x55716d7b5905]
??:? [0x55716d7b575d]
??:? [0x7f8d1b9d7189]
??:? __libc_start_main [0x7f8d1b9d7244]
??:? [0x55716d6e6ad0]
                     app INFO  2023-05-05T09:49:16.099 anisette-server-provision v2.1.0
                     app INFO  2023-05-05T09:49:16.110 Downloading libraries from Apple servers...
std.net.curl.CurlException@std/net/curl.d(4402): Couldn't resolve host name on handle 55F70D559D50
```  
I don't know why docker can't resolve host name, I can download `https://apps.mzstatic.com/content/android-apple-music-apk/applemusic.apk` on host.

**Comment by Dadoum** [comment]
Docker may use the Google DNS server by default. Try to add another dns address in `/etc/docker/daemon.json` (and restart the docker service if you are using docker)

**Comment by cccRaim** [comment]
Solved,it seems like a problem from glibc. 

https://askubuntu.com/questions/1405417/20-04-vs-22-04-inside-docker-with-a-16-04-host-thread-start-failures
