### ISSUE TITLE
builder gets stuck at 7/7

### ISSUE THREAD

**Issue by ConanArther** [Dadoum/Provision#74]
Hi,

I tried deploying it on various platforms but it always gets stuck at this step: `RUN dub build -c "static" --build-mode allAtOnce -b release --compiler=ldc2 :anisette-server`.  
Is there a fix for this?

I tried fly.io, koeyb, and render

**Comment by Dadoum** [comment]
Do you have access to more logs? This part is the most computationally expensive part of the building process, it should be the longest one, but it still should be quite fast.

**Comment by ConanArther** [comment]
> Do you have access to more logs? This part is the most computationally expensive part of the building process, it should be the longest one, but it still should be quite fast.

Thank you for your quick reply.  
nvm, after a while it was built successfully. But now SideStore keeps warnning me that the server is outdated, and my appleid keeps getting locked whenever I use the server I just created and now I'm receiving error 3667 even though the server is up and running.. Do you know how can I fix this?

**Comment by ConanArther** [comment]
Update: nvm again, I restarted the phone and everything is working perfectly now. Thank you so much!

**Comment by Dadoum** [comment]
you're welcome (I actually didn't make much). Thank you for using my software.
