### ISSUE TITLE
anisette-server seg fault on armv7

### ISSUE THREAD

**Issue by sarabveer** [Dadoum/Provision#79]
The anisette-server is seg faulting on armv7.

I have used both the latest docker image `dadoum/anisette-server` and the tagged version 2.1.0 on Github releases.

```/bin/bash: line 1:     9 Segmentation fault      (core dumped) ./anisette-server```

It segfaults on its own, without even making a HTTP call.

**Comment by Dadoum** [comment]
Okay, I just noticed glibc's `backtrace` doesn't work on armv7. I will handle the error and log it to the console.

**Comment by Dadoum** [comment]
Should be fixed, you can use the action build (when it will be finished).
