### ISSUE TITLE
Docker time error

### ISSUE THREAD

**Issue by Aransh** [Dadoum/Provision#80]
Trying to run the docker image results in this error:

`Aborting from core/time.d(2136) MonoTimeImpl!(ClockType.normal) failed to get the frequency of the system's monotonic clock.`

**Comment by Dadoum** [comment]
Can you provide more information about your system? What distro are youusing? version? CPU architecture? Which container engine are you using? Docker? Podman?

**Comment by Aransh** [comment]
Hey, yes sorry my bad
I’m using an orange pi zero, running Armbian 21.02.3 buster, arch is armv7l, and using docker

**Comment by Dadoum** [comment]
Can you try to run `hwclock --test -D` and give me the output?

Also, check if ntpd is running, try to run  `dpkg-reconfigure tzdata`, this might fix the problem.

**Comment by Aransh** [comment]
hwclock --test -D output:
hwclock: use --verbose, --debug has been deprecated.
hwclock from util-linux 2.33.1
System Time: 1688497105.736868
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
...got clock tick
Time read from Hardware Clock: 2023/07/04 18:58:24
Hw clock time : 2023/07/04 18:58:24 = 1688497104 seconds since 1969
Time since last adjustment is 1688497104 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2023-07-04 21:58:22.518770+03:00
Test mode: nothing was changed.

Seems the second command you suggested did fix the issue though! Or at least I'm getting a new error now 🙃

exec /opt/anisette_server: exec format error
exec /opt/anisette_server: exec format error
exec /opt/anisette_server: exec format error
exec /opt/anisette_server: exec format error

**Comment by Aransh** [comment]
Disregard my previous comment deleted part, it was unrelated as I forgot to turn off something unrelated.

Anyway, after running the second command, still same error, and first command output is on last comment

**Comment by Aransh** [comment]
Updated to latest armbian and the issue is gone :)
Closing this.

though I am getting a warning saying the app files are missing, which I thought should be part of the image no?
