### ISSUE TITLE
Raspbian 64-bit Anisette Server Execution Error

### ISSUE THREAD

**Issue by wkddudwo** [Dadoum/Provision#81]
root@raspberrypi:/altserver# ./anisette-server-aarch64
./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette-server-aarch64)
./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette-server-aarch64)
./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette-server-aarch64)

I tried to run the Anisette server on Raspberry Pi, but the above error occurred. Since I don't know much about cmake , I ask a question.

I don't know if there is a relationship, so I'm uploading the raspberry pi environment.

raspberry pi os 64bit

ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u5) 2.31

**Comment by wkddudwo** [comment]
> root@raspberrypi:/altserver# ./anisette-server-aarch64 ./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette-server-aarch64) ./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette-server-aarch64) ./anisette-server-aarch64: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette-server-aarch64)
> 
> I tried to run the Anisette server on Raspberry Pi, but the above error occurred. Since I don't know much about cmake , I ask a question.
> 
> I don't know if there is a relationship, so I'm uploading the raspberry pi environment.
> 
> raspberry pi os 64bit
> 
> ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u5) 2.31



>

**Comment by Dadoum** [comment]
Hello,
Thanks for your interest in my project.

It seems that you raspberry pi doesn't have the latest glibc updates. The builds in Releases are built for quite recent operating systems. You should probably try to compile it yourself on the raspberry pi. You can do it with the commands specified in the readme (install a D compiler like ldc first, then install cmake with pip, and then run the commands in the readme).

If you encounter any issue in building the project don't hesitate to ask me for help again.

**Comment by wkddudwo** [comment]
> Hello, Thanks for your interest in my project.
> 
> It seems that you raspberry pi doesn't have the latest glibc updates. The builds in Releases are built for quite recent operating systems. You should probably try to compile it yourself on the raspberry pi. You can do it with the commands specified in the readme (install a D compiler like ldc first, then install cmake with pip, and then run the commands in the readme).
> 
> If you encounter any issue in building the project don't hesitate to ask me for help again.

Thank you for your kind help. I don't know how to compile it, but I'll research it.

**Comment by wkddudwo** [comment]
> Follow the instructions in the README file, it should give you all the commands you need.

Yes, I checked the D compiler, but unfortunately it doesn't seem to support aarch64 :(

**Comment by wkddudwo** [comment]
> > Follow the instructions in the README file, it should give you all the commands you need.
> 
> Yes, I checked the D compiler, but unfortunately it doesn't seem to support aarch64 :(

(ldc-1.32.2)root@raspberrypi:/Provision# dub build -b release
     Warning WARNING: A deprecated branch based version specification is used for the dependency plist. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
    Starting Performing "release" build using /root/dlang/ldc-1.32.2/bin/ldc2 for aarch64, arm_hardfloat.
  Up-to-date provision ~main: target for configuration [plist-d] is up to date.

If you build with dub, the above will appear. What should I do next?

**Comment by Dadoum** [comment]
Run `dub build -b release :anisette-server` next to build the anisette-server executable. then you will be able to find a compiled executable to run at `bin/provision_anisette-server`.

**Comment by wkddudwo** [comment]
Thanks to Dadoum, I found a way to build and run anisette_server with aarch64. (armv7 also available)

The build method is as follows.

**Comment by wkddudwo** [comment]
> Run `dub build -b release :anisette-server` next to build the anisette-server executable. then you will be able to find a compiled executable to run at `bin/provision_anisette-server`.

Thanks to you, the build was successful! If there is a problem, I will ask again

**Comment by supermatttt** [comment]
pi@raspberrypi:~/Downloads/resource/new/Provision $ dub build -b release
Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e
