### ISSUE TITLE
Unable To Bind Websocket

### ISSUE THREAD

**Issue by ACTrooper** [Dadoum/Provision#82]
Whenever i run
```
./anisette-server-x86_64 -n 127.0.0.1 -p 6969
```
I get the error log 
```
std.socket.SocketOSException@../../../../src/libphobos/src/std/socket.d(2820): Unable to bind socket: Address already in use
----------------
../../../../src/libphobos/src/std/socket.d:2820 @trusted void std.socket.Socket.bind(std.socket.Address) [0x5584ba6cc9da]
../../../../src/libphobos/src/std/socket.d:2817 @trusted void std.socket.Socket.bind(std.socket.Address) [0x5584ba6cc9da]
??:? void handy_httpd.server.HttpServer.start() [0x5584ba4e274e]
??:? _Dmain [0x5584ba47848b]
```
Running Ubuntu 20.04, im following the guide here https://github.com/NyaMisty/AltServer-Linux/issues/99 to get AltServer working, does anybody know whats going on?

**Comment by Dadoum** [comment]
@ACTrooper any update?

**Comment by ACTrooper** [comment]
Thanks for the help @Dadoum, another anisette server was running, I restarted my computer and that killed it, making it work perfectly! it was running as a daemon and i didn't see it
