### ISSUE TITLE
An error occurred. There’s an error above. Please fix it to continue.

### ISSUE THREAD

**Issue by gaotongxue23** [Dadoum/Provision#83]
Public anisette servers are now safe on SideStore 0.4.0.But I cannot log into sidestore0.4.0 through public servers.Then, following the instructions on https://wiki.sidestore.io/guides/custom-anisette.html, I set up my own server. However, during the final step, it displayed an error message saying, "An error occurred. There's an error above. Please fix it to continue."

**Comment by dakittyl** [comment]
this has occurred to me too. even after i forked the github repo.

**Comment by tylerbouknight** [comment]
Encountered the same. Instead of forking, try creating a new repo then uploading the code from this one. That way it doesn't show as a fork - this is what worked for me :)

**Comment by dakittyl** [comment]
How do I upload the code from this repo?

**Comment by tylerbouknight** [comment]
After you hit “create repository” the next page, where it shows the “create a codespace” and “invite collaborators” options at the top, the last box should say “…or import code from another repository.” Hit the import code button, copy the url of the repo you want to clone (main page) and paste it in the little url box. Hit begin import and you should be set. Let me know if I need to further clarify.

**Comment by gaotongxue23** [comment]
> After you hit “create repository” the next page, where it shows the “create a codespace” and “invite collaborators” options at the top, the last box should say “…or import code from another repository.” Hit the import code button, copy the url of the repo you want to clone (main page) and paste it in the little url box. Hit begin import and you should be set. Let me know if I need to further clarify.

Thank you very much. Through your method, I have successfully created a new server.
